# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/prarthanamahesh21-hub/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*Name your lane — or say 'freestyle' and describe your own question. One short paragraph: why this one?*

  File "/tmp/ipykernel_1403/3123674299.py", line 1
    I will focus on identifying which content pages should be reviewed first for a possible content refresh. I chose this lane because the dataset contains page-level search, engagement, content-age, and performance signals that can help prioritize pages for review. The goal is not to automatically declare that a page needs a refresh, but to create a useful ranking that helps an editor or SEO reviewer decide where to investigate first.
      ^
      

## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*

### The question

**Search question:**
Which content pages should be reviewed first for a potential refresh, based on their observable search performance, content age, engagement, and visibility signals?

**Decision:**
Decide which pages should receive editorial or SEO review first.

**Unit of analysis:**
One content page.

**Output:**
A ranked list of content pages with an opportunity or priority score.

**Action:**
An editor or SEO reviewer can inspect the highest-ranked pages and decide whether a content refresh or further investigation is appropriate.

**Cost of a wrong recommendation:**
A false positive could waste limited editorial effort on a page that is not a priority. A false negative could cause an important page with a potential improvement opportunity to be overlooked.

The goal is therefore to support prioritization, not to automatically decide that a page must be refreshed.


## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

### Quick look at the data

The starter dataset contains **30,000 content pages** across **32 unique clients** and **44 columns** of page-level information. The median content age is **236 days**, and **17,728 pages are older than 180 days**.

These numbers make the refresh-prioritization problem worth investigating because the dataset contains a large number of pages and a substantial portion of them are relatively old. A ranked review queue could help an editor or SEO team decide which pages to investigate first instead of manually reviewing every page. However, content age alone does not mean that a page needs a refresh, so other search and engagement signals will also need to be considered.


In [18]:
import pandas as pd

url = "https://raw.githubusercontent.com/prarthanamahesh21-hub/flyrank-ml-internship/main/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(url)

print("Number of pages:", len(df))
print("Number of columns:", len(df.columns))
print("Number of unique clients:", df["client_id"].nunique())

Number of pages: 30000
Number of columns: 44
Number of unique clients: 32


In [19]:
print("Median content age (days):", df["content_age_days"].median())
print("Pages older than 180 days:", (df["content_age_days"] > 180).sum())

Median content age (days): 236.0
Pages older than 180 days: 17728


## 4. Careful words: what I can and can't claim

*Write what your work will be able to say (observed, directional, decision-support) — and what it never will (causal proof, 'predicting Google').*

### What I can and cannot claim

**What I can claim:**
The dataset provides page-level search, engagement, content-age, and other observable signals that can be used to investigate whether pages can be prioritized for review. The size and structure of the dataset make it reasonable to explore a ranking approach for editorial review.

**What I cannot claim yet:**
I cannot claim that a particular page definitely needs a refresh, that a high opportunity score will cause better search performance, or that an ML model will outperform a simple rule until those claims are tested. A ranking should be treated as decision support for further review rather than as proof that a refresh will improve a page's performance.


## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

### Self-check

* **Lane:** Refresh / Content Opportunity Scoring
* **Unit of analysis:** One content page
* **Decision:** Which pages should be reviewed first?
* **Action:** An editor or SEO reviewer investigates the highest-priority pages and decides whether further review or a refresh is appropriate.
* **Output:** A ranked list of pages with an opportunity or priority score.
* **Cost of a wrong recommendation:** Wasted editorial effort or failure to review a potentially important page.
* **Data evidence:** 30,000 pages, 32 unique clients, and 17,728 pages older than 180 days.
* **Why data/ML may help:** Multiple page-level signals can potentially be combined to prioritize review more effectively than a single fixed rule.
* **Careful claim:** The ranking is decision support, not proof that a page needs a refresh or that refreshing it will improve performance.
